version: 2.1

orbs:
  deploy: snyk/deploy@2
  prodsec: snyk/prodsec-orb@1

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: alerts-security-labs
